### ISSUE TITLE
Possible bug related to parameter names with dashes and string values

### ISSUE THREAD

**Issue by asm2git** [trlinkin/trlinkin-sysctl#1]
Test case 1:

```
sysctl { 'net.bridge.bridge-nf-call-arptables':
  value => 0,
 }
```

Error message 1:

```
err: Failed to apply catalog: Cannot find kernel parameter 'net.bridge.bridge-nf-call-arptables' on system. at /etc/puppetlabs/puppet/modules/sysctl_example/manifests/init.pp:6
```

Test case 2:

```
sysctl { 'net.ipv4.tcp_rmem':
  value => '4096 131072 16777216',
}
```

Error message 2:

```
err: Failed to apply catalog: Cannot find kernel parameter 'net.ipv4.tcp_rmem' on system. at /etc/puppetlabs/puppet/modules/sysctl_example/manifests/init.pp:6
```

Other parameters without dashes in their names work; parameters that are single integers work -- so I'm guessing the parsing isn't as complete/robust as it needs to be. Sorry, but I don't know Ruby well enough to read the code and see if that's actually the case.

I'm trying to use this module in production and not having these parameters and values is going to cause problems for me; if there's any way you could please fix this I'd really appreciate it. On the other hand, if your code is correct and the problem is how I'm using it, could you please show me where I got it wrong?

Thanks.

**Comment by trlinkin** [comment]
Adam,

For the first kernel parameter (net.bridge.bridge-nf-call-arptables), I would like you to check that the system has that parameter available. The resource checks to make sure the parameter exists before you can control it. I may add a force option later.   

For the second kernel parameter (net.ipv4.tcp_rmem), you are correct, this is a parsing mistake. I've just pushed a commit that should correct it. I still need to run it through the spec tests, and make an official release for the Forge. I'm thinking an original release may occur later this week, but feel free to test what I've done.

**Comment by asm2git** [comment]
Tom,

Thanks for looking into this.

> For the first kernel parameter (net.bridge.bridge-nf-call-arptables), I
> would like you to check that the system has that parameter available.

Ah-ha! There is indeed no such parameter. I'm working on a system I
didn't build and don't control, and just blindly took whatever was in
/etc/sysctl.conf and coded that into my Puppet module. Nevermind. :-)

> For the second kernel parameter (net.ipv4.tcp_rmem), you are correct, this
> is a parsing mistake. I've just pushed a commit that should correct it.

Thanks.

Adam
